# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gamebot_pb2 as gamebot__pb2


class GameBotStub(object):
    """Описание сервиса
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAction = channel.unary_unary(
                '/gamebot.GameBot/SendAction',
                request_serializer=gamebot__pb2.Action.SerializeToString,
                response_deserializer=gamebot__pb2.ActionResponse.FromString,
                )


class GameBotServicer(object):
    """Описание сервиса
    """

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameBotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=gamebot__pb2.Action.FromString,
                    response_serializer=gamebot__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gamebot.GameBot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GameBot(object):
    """Описание сервиса
    """

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gamebot.GameBot/SendAction',
            gamebot__pb2.Action.SerializeToString,
            gamebot__pb2.ActionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
