# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamebot.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgamebot.proto\x12\x07gamebot\"0\n\x06\x41\x63tion\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x10\n\x08\x64uration\x18\x03 \x01(\x05\" \n\x0e\x41\x63tionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2A\n\x07GameBot\x12\x36\n\nSendAction\x12\x0f.gamebot.Action\x1a\x17.gamebot.ActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamebot_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ACTION']._serialized_start=26
  _globals['_ACTION']._serialized_end=74
  _globals['_ACTIONRESPONSE']._serialized_start=76
  _globals['_ACTIONRESPONSE']._serialized_end=108
  _globals['_GAMEBOT']._serialized_start=110
  _globals['_GAMEBOT']._serialized_end=175
# @@protoc_insertion_point(module_scope)
